version: '3.2'
services:
  rasa_core:
    container_name: rasa_core
    image: rasa/rasa:3.3.0-full
    environment:
      - endpoints=endpoints.yml
      - RASA_MAX_CACHE_SIZE=0
    volumes:
      - ./app:/app
    command:
      - run

  rasa_action_server:
    build:
      context: ./action_server
      dockerfile: Dockerfile
    container_name: rasa_action_server
    image: rasa_action_server
    environment:
    depends_on:
      - rasa_core
    volumes:
      - ./app/actions:/app/actions

  # rasa_tracker_store:
  #   container_name: rasa_tracker_store
  #   image: postgres
  #   environment:
  #   - POSTGRES_USER=rasa
  #   - POSTGRES_PASSWORD=rasa
  #   - POSTGRES_DB=rasa